version: '2'

volumes:
  postgres-data:

services:

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oil_level
      POSTGRES_USER: oil_level_user
      POSTGRES_PASSWORD: password

  oil-level-monitor:
    image: registry.gitlab.com/ledsys/oil-level-monitor:0.1.0
    ports: ["8120:8120"]
    environment:
      RUST_BACKTRACE: full
