local:
	DATABASE_HOST="localhost" DATABASE_PORT="5431" DATABASE_USERNAME="oil_level_user" DATABASE_PASSWORD="password" mvn clean process-resources

docker:
	docker build -t oil-level-monitor-liquibase:latest .